### ISSUE TITLE
Add Suite with examples extension

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#104]
To make screenshots like https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/blob/master/Documentation/Images/ManualScreenshots/PluginFlexFormConfigurationCheck.png

There are many more screenshots from this extension in the TSref Reference

**Comment by linawolf** [comment]
This one also is from the examples extension: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/blob/master/Documentation/Images/ManualScreenshots/ExtendingTcaFeUsers.png

**Comment by alexander-nitsche** [comment]
Would you add a link to the examples extension.

**Comment by linawolf** [comment]
https://extensions.typo3.org/extension/examples or https://github.com/TYPO3-Documentation/TYPO3CMS-Code-Examples

**Comment by alexander-nitsche** [comment]
Is additional effort required for installation than requiring the package and activating it in the Extension Manager?

**Comment by alexander-nitsche** [comment]
Related to https://github.com/TYPO3-Documentation/TYPO3CMS-Code-Examples/issues/25.
