### ISSUE TITLE
Screenshots of Content Elements not found in introduction

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#105]
Like the following:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/blob/master/Documentation/Images/ManualScreenshots/OuterFieldWizard.png

**Comment by alexander-nitsche** [comment]
Does this mean it is missing in the introduction package and has formerly been added manually to a TYPO3 instance before taking the screenshot? Would the solution be to add it to the introduction package, the styleguide package or the testing environment of one of both only?

**Comment by linawolf** [comment]
It is not missing in the introduction package but an example that you would usually just add by hand into your TYPO3 installation

**Comment by alexander-nitsche** [comment]
Ok, in this project we have to use XML fixtures for introducing custom dataset into the TYPO3 environment. Do you want to provide a fixture?

**Comment by linawolf** [comment]
How would I do that?

**Comment by alexander-nitsche** [comment]
Mh, skip the XML fixture and let us take the Documentation Team internal [EXT:examples](https://github.com/TYPO3-Documentation/TYPO3CMS-Code-Examples.git) extension to create all custom elements for the TYPO3 documentation. Let's wait for the [conversion of the extension into a distribution](https://github.com/TYPO3-Documentation/TYPO3CMS-Code-Examples/issues/25) and then continue here.

**Comment by alexander-nitsche** [comment]
The conversion of the `EXT:examples` into a distribution is done. Next, the custom element could be created there, following the docs in section "[Custom content elements](https://github.com/TYPO3-Documentation/t3docs-screenshots#id13)".

**Comment by linawolf** [comment]
Works fine, thx
