### ISSUE TITLE
Screenshots of module fails when run in context

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#113]
When I have the following in my screenshots.json:

```
"inline_fal": [
          {
            "action": "goToField",
            "fields": "inline_1"
          },
....
        ],
        "overview": [
          {"action": "resizeWindow", "width": 1220,"height": 440},
          {"action": "see", "text": "List"},
          {"action": "click", "link": "List"},
...
        ],
````

"overview" will run if it is run by itself:
``
 ddev make-screenshots -t TYPO3CMS-Reference-TCA -s Styleguide -a overview
``

However it will fail if run in context:
`` 
 ddev make-screenshots -t TYPO3CMS-Reference-TCA -s Styleguide 
or
 ddev make-screenshots -t TYPO3CMS-Reference-TCA
``

**Comment by alexander-nitsche** [comment]
Yes, navigating the browser to an explicit content frame url, as done with action `goToField`, leaves the page with the content frame only - no module menu, no header. So the following action `see` will not succeed as it looks for a module menu item. It is good practice to reload the complete backend via action `reloadBackend` when done with the content frame actions:
```
"inline_fal": [
  {
    "action": "goToField",
    "fields": "inline_1"
  },
  ...
  {
    "action": "reloadBackend"
  }
],
"overview": [
  {"action": "resizeWindow", "width": 1220,"height": 440},
  {"action": "see", "text": "List"},
  {"action": "click", "link": "List"},
  ...
]
```
The basic configuration does the same, see [here](https://github.com/TYPO3-Documentation/t3docs-screenshots/blob/main/packages/screenshots/Classes/Configuration/Configuration.php#L277).

**Comment by linawolf** [comment]
This can be simplified by https://github.com/TYPO3-Documentation/t3docs-screenshots/issues/122 in future, for now we have to reset everything manually
