### ISSUE TITLE
Take a screenshot of the Install Tool

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#115]
When I am trying to take a screenshot of the Install Tool I get asked for the password. How can I enter the password or circumference this?

```
{
    "suites": {
        "Core": {
            "screenshots": [
                [
                    {"action": "resizeWindow", "width": 1024,"height": 768},
                    {"action": "see", "text": "Maintenance"},
                    {"action": "click", "link": "Maintenance"},
                    {"action": "makeScreenshotOfFullPage", "fileName": "AdminToolsMaintenanceOverview"}
                ]
            ]
        }
    }
}
```

**Comment by alexander-nitsche** [comment]
When browsing the TYPO3 instance in the browser that modal is not shown as the TYPO3 instance runs in `Development` context. The runner runs the TYPO3 instance in `Testing` context and has to pass that modal. Setting the context to Production temporarily let me understand the modal: It is not displayed in the main frame but in the content frame, and is not fading in, but displayed immediately, and does not contain the class `.show` which is used by the modal specific actions `waitForModalDialogInMainFrame` and `clickButtonInModalDialog`. It can be seen as a regular formular with modal look. The following actions let you pass it and proceed to the maintenance page:
```
"installTool": [
    {"action": "resizeWindow", "width": 1024,"height": 768},
    {"action": "see", "text": "Maintenance"},
    {"action": "click", "link": "Maintenance"},
    {"action": "switchToContentFrame"},
    {"action": "fillField", "field": "input#confirmationPassword", "value": "password"},
    {"action": "click", "link": "Confirm"},
    {"action": "waitForText", "text": "Maintenance", "timeout": 5},
    {"action": "makeScreenshotOfFullPage", "fileName": "InstallTool"}
]
```

**Comment by linawolf** [comment]
Worked fine
