### ISSUE TITLE
Error on running examples screenshot.json 

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#123]
Running the following:

ddev install

ddev init-screenshot-json

ddev make-screenshots -t My-Manual

I currently get 4 Failures:

```
4) StyleguideCest: Make screenshots
 Test  Codeception/Styleguide/StyleguideCest.php:makeScreenshots
Found following JavaScript errors in the browser console:
09:40:47.774 SEVERE - http://web/typo3temp/var/tests/acceptance/typo3/index.php - Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by alexander-nitsche** [comment]
You probably have missed to complete the TYPO3 installation. See (2) "Navigate in your browser to the website and complete the installation:" of https://github.com/TYPO3-Documentation/t3docs-screenshots#installation.

**Comment by linawolf** [comment]
This + a complete ddev poweroff + ddev start solved this for me
