### ISSUE TITLE
Error message when json has a syntax error

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#160]
When the screenshots.json has a Syntax error (like a trailing comma) the script just ends without any message what happened. It would be great if there was an error message stating that there was a syntax error and in which file

**Comment by linawolf** [comment]
I cannot see how your PR would fix this issue as I am talking about a syntax errror in the **screenshots.json** not about code snippets of JSON files

**Comment by alexander-nitsche** [comment]
Test it.

**Comment by alexander-nitsche** [comment]
Is an error message thrown?

**Comment by linawolf** [comment]
yes, wonderfull
