### ISSUE TITLE
Take Screenshot of Examples frontend

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#164]
Trying to take a screenshot of the frontend:
```
{
  "suites": {
    "Examples": {
      "screenshots": {
        "_default": [
          {"action": "resizeWindow", "width": 640,"height": 640},
          {"action": "setScreenshotsDocumentationPath", "path": "Documentation"},
          {"action": "setScreenshotsImagePath","path": "Images/AutomaticScreenshots"},
          {"action": "setScreenshotsRstPath","path": "Images/AutomaticScreenshots"},
          {"action": "setCodeSnippetsSourcePath","path": "typo3conf/ext/examples"},
          {"action": "setCodeSnippetsTargetPath", "path": "CodeSnippets"}
        ],
        "hmenuSpecial": [
          {"include": "_default"},
          {"action": "resizeWindow", "width": 480,"height": 640},
          {"action":  "amOnPage", "page": "/hmenu-special-userfunc"},
          {
            "action": "makeScreenshotOfElement",
            "fileName": "ContentObjectsHmenuExampleMenu",
            "altText": "Output of the example menu"
          }
        ]
      }
    },
```

![TYPO3 CMS Screenshots Runner Codeception Examples ExamplesCest makeScreenshots fail](https://user-images.githubusercontent.com/48202465/124157698-57092280-da99-11eb-8e06-198322ab996f.png)

I get an error that the site configuration is missing.  Opening the frontend of the page manually works fine however.
[TYPO3.CMS.Screenshots.Runner.Codeception.Examples.ExamplesCest.makeScreenshots.fail.html.zip](https://github.com/TYPO3-Documentation/t3docs-screenshots/files/6749603/TYPO3.CMS.Screenshots.Runner.Codeception.Examples.ExamplesCest.makeScreenshots.fail.html.zip)

**Comment by alexander-nitsche** [comment]
Hi Lina, 
please post here the site configuration or the link to it. I assume, that the base url in the site configuration is not right: the base url for the screenshot runner is `http(s)://web` compared to `http(s)://t3docs-screenshots.ddev.site` for manual browsing.
Greetings,
Alex

**Comment by linawolf** [comment]
Problem is, the site configuration is created automatically on doing the screenshot run. there is no site configuration in the project itself. 
It is the same problem with the introduction and the examples Suites. the one generated
[config.yaml.txt](https://github.com/TYPO3-Documentation/t3docs-screenshots/files/6797216/config.yaml.txt)

I attached the one from introduction. It is not using a base url

**Comment by alexander-nitsche** [comment]
This seems to be an Nginx configuration issue: It is currently not configured for frontend urls, especially not for SEF urls.

**Comment by linawolf** [comment]
So we cannot do frontend screenshots?

**Comment by alexander-nitsche** [comment]
Not with the current implementation of the nginx configuration. Would be an enhancement.

**Comment by linawolf** [comment]
Ok, I updated the title accordingly

**Comment by linawolf** [comment]
[screenshots.json.txt](https://github.com/TYPO3-Documentation/t3docs-screenshots/files/6982204/screenshots.json.txt)

**Comment by linawolf** [comment]
Funny thing is that in https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Installation/blob/master/screenshots.json, line 384 there is a screenshot of the introduction frontend taken and it is working...

**Comment by linawolf** [comment]
This might be due to the fact that the introduction package has a site configuration at 
Initialisation/Site/introduction/config.yaml 

?

**Comment by alexander-nitsche** [comment]
hi @linawolf , can this issue be closed?

**Comment by linawolf** [comment]
Whoops yeah has been solved since august
