### ISSUE TITLE
ddev install doen't work anymore for me

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#168]
I always get the following error:

Failed to start project for custom command: container failed to become healthy: err=health check timed out: labels map[com.ddev.site-name:t3docs-screenshots] timed out without becoming healthy, status=

I tried everything, even deleting the whole project and redoing it. no success always the same error. Doing ddev restart or such works fine...

**Comment by alexander-nitsche** [comment]
Works still fine on my side. Please tell if
```
ddev poweroff
ddev install
```
does not work either and if so, what happens if you remove the project and do a simple start of it:
```
ddev delete -yO
ddev start
```
Does it show the same error? Which versions of DDEV and docker do you use?

**Comment by linawolf** [comment]
ddev delete -yO
ddev start

worked for me
