### ISSUE TITLE
Handle scrolling of modal body `iframe` in actions `scrollModalDialogTo*` 

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#180]
The following does not scroll even though there is more then enough space to scroll

Suite Introduction:
```

        "BackendGroups": [
          {"include": "_default"},
          {
            "action": "setScreenshotsImagePath",
            "path": "Images/AutomaticScreenshots/BackendGroups"
          },
          {
            "action": "setScreenshotsRstPath",
            "path": "Images/AutomaticScreenshots/BackendGroups"
          },
          {"action": "switchToMainFrame"},
          {
            "action": "click",
            "link": "Backend Users"
          },
          {"action": "switchToContentFrame"},
          {
            "action": "selectOption",
            "select": "select.t3-js-jumpMenuBox",
            "option": "Backend user groups"
          },
          {
            "action": "waitForText",
            "text": "Backend User Group Listing",
            "timeout": 5
          },
          {
            "action": "click",
            "link": "tr:first-child a[data-dispatch-action=\"TYPO3.InfoWindow.showItem\"]"
          },
          {
            "action": "waitForModalDialogInMainFrame"
          },
          {
            "action": "scrollModuleMenuToBottom"
          },
          {
            "action": "wait",
            "timeout": 1
          },
          {
            "action": "makeScreenshotOfElement",
            "fileName": "GroupDetail",
            "captionText": "Checking out which users are part of the group"
          }
        ],

```
![GroupDetail](https://user-images.githubusercontent.com/48202465/125210165-4a0ce000-e29e-11eb-9bac-1b0924af6aec.png)

**Comment by alexander-nitsche** [comment]
This is due to scrolling is done in an `iframe` child element of the modal body instead of the modal body itself. Requires additional handling in the modal implementation.

**Comment by linawolf** [comment]
In the above example using "scrollModalDialogFrameToBottom" leads to the following error:

```javascript error: Cannot read property 'scrollHeight' of null```

See here: https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/blob/8c643765496e219a643d7c220fa482d2eac4ee34/screenshots.json#L196

**Comment by alexander-nitsche** [comment]
Yes, i mentioned in the PR that the handling of a modal dialog frame requires to jump into the modal dialog first - as you have to with main and content frame already. See https://github.com/TYPO3-Documentation/t3docs-screenshots/pull/181#issue-687948927 .

**Comment by linawolf** [comment]
Ah sorry, must have missed that part. It worked
