### ISSUE TITLE
Opening third level pages

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#182]
Opening third level pages in the pagetree seems to always fail, at least in the introduction package:
`` {"action": "openPageTreePath", "path": ["Congratulations", "Pages", "Default"]},``
or 
`` {"action": "openPageTreePath", "path": ["Congratulations", "Content Examples", "Form elements"]},``
cause the following error:
```
Failed asserting that any element by 'g.nodes > .node' on page /typo3temp/var/tests/acceptance/typo3/module/system/BeuserTxPermission[total 12 elements]
contains text 'Default'
```

![TYPO3 CMS Screenshots Runner Codeception Introduction IntroductionCest makeScreenshots fail](https://user-images.githubusercontent.com/48202465/125922081-669d46df-75e8-499a-8498-8a3df7ee9171.png)
[TYPO3.CMS.Screenshots.Runner.Codeception.Introduction.IntroductionCest.makeScreenshots.fail.html.txt](https://github.com/TYPO3-Documentation/t3docs-screenshots/files/6829329/TYPO3.CMS.Screenshots.Runner.Codeception.Introduction.IntroductionCest.makeScreenshots.fail.html.txt)

**Comment by alexander-nitsche** [comment]
This might be related to issue #162 .

Please check if replacing the first action by
`{"action": "openPageTreePath", "path": ["Congratulations"]},`
and
`{"action": "openPageTreePath", "path": ["Congratulations", "Pages"]},`
and
`{"action": "openPageTreePath", "path": ["Congratulations", "Pages", "2 Columns"]},`
succeed respectively.

**Comment by linawolf** [comment]
{"action": "openPageTreePath", "path": ["Congratulations"]},

and 


{"action": "openPageTreePath", "path": ["Congratulations", "Pages"]},

do work.

you can find it in 

https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/blob/4f32febce98eb3cf24920ed0c8570586f5acea54/screenshots.json#L503

**Comment by alexander-nitsche** [comment]
And what about 
`{"action": "openPageTreePath", "path": ["Congratulations", "Pages", "2 Columns"]}`
?

**Comment by linawolf** [comment]
That one fails with the same error as the above examples

**Comment by alexander-nitsche** [comment]
Created an issue in the testing-framework here: https://github.com/TYPO3/testing-framework/issues/245
