### ISSUE TITLE
Open and close Sections in Module menu

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#183]
I do often need screenshots that show where in the module menu the module can be found. usually it is a good thing to close all sections and just open the section you need. Afterwards to "clean up" i need to open everything back up. Everything I tried didn't work out except always waiting a second. This leads to long and not nice sections for a simple task. Can we somehow simplify this? It takes a long time to run and it is just confusing to have it like that in the json.

```

          {"comment": "Close all Module Sections"},
          {"action": "switchToMainFrame"},
          {"action": "click", "link": "button#web"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#site"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#file"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#system"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#tools"},
          {"action": "wait", "timeout": "1"},

  {"comment": "Modules Admin Tools"},
          {"comment": "************************************"},

          {"action": "click", "link": "button#tools"},
          {"action": "wait", "timeout": "1"},
          {"action": "scrollModuleMenuTo", "toSelector":  "button#system"},
...

          {"action": "click", "link": "button#tools"},
          {"action": "wait", "timeout": "1"},
          {"comment": "************************************"},
          {"comment": "Modules System"},
etc...

          {"comment": "Open all Module Sections again"},
          {"action": "click", "link": "button#web"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#site"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#file"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#system"},
          {"action": "wait", "timeout": "1"},
          {"action": "click", "link": "button#tools"},
          {"action": "wait", "timeout": "1"}
```

**Comment by alexander-nitsche** [comment]
To show the menu item you could use action `scrollModuleMenuTo` instead.

**Comment by linawolf** [comment]
I do want to make pictures like these:
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/_images/CreateNewGroup.png

Scrolling doesn't give me the same overview over the module menu

**Comment by alexander-nitsche** [comment]
Mh, i would keep it streamlined and decide to always show the menu folded or always scroll to the menu item. With the current implementation it is intended to always scroll to the menu item: Are you sure, that your new approach is worth the additional effort? The default backend module menu is unfolded so at least i would prefer to see it like that in the documentation too.

Nevertheless, what would happen, if you remove all timeouts except the last one:

```json
{"comment": "Close all Module Sections"},
{"action": "switchToMainFrame"},
{"action": "click", "link": "button#web"},
{"action": "click", "link": "button#site"},
{"action": "click", "link": "button#file"},
{"action": "click", "link": "button#system"},
{"action": "click", "link": "button#tools"},
{"action": "wait", "timeout": "1"},
```

**Comment by linawolf** [comment]
If I don't wait in between the clicks fail. If I wait for the submenu by id then it gets only half loaded. 

If you compare the two screenshots:
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/_images/CreateNewUser.png

And 
https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/_images/BeUsersModule.png

I just think, that the earlier one gives the better overview and is cleaner and less distracting. And it has often been done like that in manual screenshots. Of course that is a philosophical question. As it is it however messes up the whole screenshot.json and is hard to controll.

Except in rare cases where we want to show an overview of the complete backend this would be my prefered way of doing it....

**Comment by alexander-nitsche** [comment]
What does "clicks fail" mean: Is there an error thrown?

**Comment by linawolf** [comment]
I am sorry, I don't have the json like that anymore. I just kept trying until some setup did what I need. So I can't get the exact error for you but yes there where error messages. Something like: "Another element would receive the click" or Element not found as it would flow out of focus by the other parts still moving

**Comment by alexander-nitsche** [comment]
Ok. I suggest to keep using the action `scrollModuleMenuTo` in an unfolded module menu for the moment. And you can create a new issue of type "enhancement" with the target to create a next module menu action which folds the menu accordingly which can then be easily applied to all screenshots.json by search & replace for `scrollModuleMenuTo`.

**Comment by linawolf** [comment]
Thats a good idea
