### ISSUE TITLE
Remove goToTable and takeScreenshotOfTable

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#227]
These functions are to seldom used and a special case.

They can be replaced by using the list module

**Comment by alexander-nitsche** [comment]
There seems to be a misspelled `GoToTable` in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/blob/master/Documentation/screenshots.json additionally.

**Comment by linawolf** [comment]
true, I will remove it
