### ISSUE TITLE
Documentation: Clarification of TYPO3 version

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Documentation/t3docs-screenshots#239]
One thing I stumbled across: The project is getting version 11.x and it's working so far. Is functionality with v10 actually possible? If not, I would add something to the documentation at the beginning that it is currently still running under v11.

An adaptation to v10 would presumably mean that all examples etc. would have to be updated as well?

**Comment by linawolf** [comment]
We do not have a version for 10 as we started with 11 right away. And also we have neither manpower nor funds to provide funtctionality for Version 10 right now. I think the composer.json clearly states so?

**Comment by ayacoo** [comment]
Here too: No problem ;-) I would then create a PR to add this note in the documentation.

**Comment by DavidBruchmann** [comment]
I added the hint to #238, so I close this issue.
