### ISSUE TITLE
Investigations - Recherche

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/t3docs-screenshots#3]
### Possible JavaScript Frameworks

* https://github.com/ailon/markerjs2

### How to screenshot DOM elements

* https://www.startpage.com/do/dsearch?query=screenshot+dom+element 

### What is already defined?

* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/GuidelinesForImages.html
*

**Comment by linawolf** [comment]
I think basic investigations are done...
