### ISSUE TITLE
How to wait for a select tree to load?

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#35]
Pictures of select trees need to wait for the tree to load, 

i.e. public/t3docs-generated/actual/TYPO3CMS-Reference-TCA/Documentation/Images/AutomaticScreenshots/SelectTree1.png

Pupeteer Syntax was:

{
              "field": "select_tree_1",
              "actions": [
                {
                  "action": "wait",
                  "timeout": "100"
                }
              ]
            },

**Comment by alexander-nitsche** [comment]
To wait for a fixed time period you can use e.g.
```
{"action": "wait", "timeout": 0.1}
```
and to wait for a specific DOM element to appear, for a given upper limit of time, you can use e.g.
```
{"action": "waitForElement", "element": "#my-element", "timeout": 1}
```

See 
- \TYPO3\CMS\Screenshots\Runner\Codeception\Support\_generated\BackendTesterActions::wait
- \TYPO3\CMS\Screenshots\Runner\Codeception\Support\_generated\BackendTesterActions::waitForElement
- and many other \TYPO3\CMS\Screenshots\Runner\Codeception\Support\_generated\BackendTesterActions::wait*

**Comment by linawolf** [comment]
Works fine
