### ISSUE TITLE
How to open an accordion?

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#36]
In the inline screenshots I need to open the first accordion, old syntax:

 {
              "field": "inline_1",
              "actions": [
                {
                  "action": "open",
                  "accordion": "@first"
                }
              ]
            }

and in some the first accordion within the first accordion:

            {
              "field": "inline_1",
              "actions": [
                {
                  "action": "open",
                  "accordion": "@first"
                },
                {
                  "action": "open",
                  "accordion": ".form-irre-object .panel-collapse .form-irre-header-button"
                }
              ]
            }

**Comment by alexander-nitsche** [comment]
Taking the puppeteer implementation into account i would suggest something like:
```
{"action": "click", "link": ".form-irre-header-button"}
{"action": "click", "link": ".form-irre-object .panel-collapse .form-irre-header-button"}
```
and maybe you need to add some wait actions here too. If that does not work out, would you point me to a TYPO3 backend page with an accordion?

**Comment by linawolf** [comment]
Works fine, had no problem with toggling yet.
