### ISSUE TITLE
How to change record types?

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#38]
Including Screenshot of the modal and clicking the ok button to really change the modal.

Examples:
public/t3docs/TYPO3CMS-Reference-TCA/Documentation/Includes/Images/Styleguide/AutomaticScreenshots/CtrlType0.png
public/t3docs/TYPO3CMS-Reference-TCA/Documentation/Includes/Images/Styleguide/AutomaticScreenshots/CtrlType1.png
etc

**Comment by alexander-nitsche** [comment]
Changing a select field can be achieved e.g. by
```
{"action": "selectOption", "select": "[name='data[pages][26][doktype]']", "option": "6"}
```
See \TYPO3\CMS\Screenshots\Runner\Codeception\Support\_generated\BackendTesterActions::selectOption.

Confirming a modal overlay we will have a new action for it which is not yet implemented but already in the testing-framework: vendor/typo3/testing-framework/Classes/Core/Acceptance/Helper/AbstractModalDialog.php. I would wait for it, i will do it in the next few days.

**Comment by alexander-nitsche** [comment]
To confirm the modal overlay without the new action, you could insert these 5 actions:
```
{"action": "switchToIFrame"},
{"action": "waitForElement", "element": ".modal.in"},
{"action": "wait", "timeout": 2},
{"action": "click", "link": "", "context": ".modal.in .modal-footer"},
{"action": "waitForElementNotVisible", "element": ".modal.in"}
```
