### ISSUE TITLE
Debugging backend functions

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#45]
In the old setup I was taking the screenshots in the same enviroment that I could also access myself. So I could take a look at the tree example from the styleguide example in the backend that I can access as a user myself. Then I could check which class needs to be loaded in order for the tree to be properly loaded or some such.

Could we make it possible to load one distribution or the other in the very backend that we can access?

**Comment by alexander-nitsche** [comment]
For browsing the TYPO3 instance you could follow the installation instructions of https://github.com/TYPO3-Documentation/t3docs-screenshots#installation: Install TYPO3 and activate the page tree of EXT:introduction or EXT:styleguide. Then browse the instance, take notes of the classes etc. and write actions.

**Comment by linawolf** [comment]
That solves it for me, Thank you
