### ISSUE TITLE
Manager: Enable selection of images to copy

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/t3docs-screenshots#51]
The screenshot manager backend module should enable the user to select a subset of images for copying and offer aggregation checkboxes: 

- all
- none

**Comment by linawolf** [comment]
Maybe aggregation by path?

**Comment by alexander-nitsche** [comment]
I could imagine a new filter for that in combination with aggregation selection "all". The new filter could be either a search field which matches against the file paths, or it could be a select box which simply lists all available paths. In either case this should be a new enhancement issue.
