### ISSUE TITLE
Manager: Make it mobile ready

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/t3docs-screenshots#55]
The screenshot manager backend module should offer a reduced but intuitive panel on mobile devices.

**Comment by linawolf** [comment]
Why should we need the screenshot manager to use on mobile? Are you planning to run ddev on a mobile device?

**Comment by alexander-nitsche** [comment]
The DDEV instance could be hosted in the pampa or the djungle as long as it has public internet access :)

**Comment by alexander-nitsche** [comment]
Skip it for now.
