### ISSUE TITLE
Selector Dropdown is displayed strangely

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#66]
![SelectorDropdown](https://user-images.githubusercontent.com/48202465/117527605-99e4d780-afcd-11eb-986f-eabdb2d2a07f.png)

The example can be found in the TCA Manual, Filename `CtrlType`

**Comment by alexander-nitsche** [comment]
I can confirm that. This will have to be investigated further.

**Comment by alexander-nitsche** [comment]
I can reproduce the issue in Codeception as well as in the bundled package `php-webdriver/webdriver`. It is either a problem with that package, or with the bundled Selenium standalone server, or with the bundled Chrome Driver + Chrome Browser. I started to report the issue for the `php-webdriver` level and will drive it through all layers:

https://github.com/php-webdriver/php-webdriver/issues/905
