### ISSUE TITLE
How to click tab by Text?

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#67]
I tried:

``
 {
            "action": "click",
            "link": "//*[text()[contains(.,'Access')]]"
          },
``

to no awail. Should I use XPath? https://stackoverflow.com/questions/3655549/xpath-containstext-some-string-doesnt-work-when-used-with-node-with-more

**Comment by alexander-nitsche** [comment]
Xpath would work, although I'm not immediately sure of the correct pattern. Instead of specifying a pattern, you can also specify the link text itself:

```
{"action": "click", "link": "Access"}
```

However, you should make sure that this link text is unique in your current frame. 

A complete working example would be

```
{"action": "see", "text": "List"},
{"action": "click", "link": "List"},
{"action": "openPageTreePath", "path": ["styleguide TCA demo", "elements rte"]},
{"action": "switchToContentFrame"},
{"action": "waitForText", "text": "elements rte", "timeout": 5},
{"action": "click", "link": "elements rte - language 4"},
{"action": "waitForText", "text": "Edit Page \"elements rte - language 4\"", "timeout": 5},
{"action": "click", "link": "Access"},
{"action": "makeScreenshotOfFullPage", "fileName": "page_tab_access"}
```

**Comment by linawolf** [comment]
waitForText did the trick
