### ISSUE TITLE
Error on Copying Rst files

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#68]
On Copying Rst files I get an error now:

``
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: copy(/var/www/html/public/t3docs/TYPO3CMS-Reference-TCA/Documentation/Images/Rst/Checkbox12.rst.txt): failed to open stream: No such file or directory in /var/www/html/packages/screenshots/Classes/Controller/ScreenshotsManagerController.php line 147
``

The file does not exist as it is the target, not the source. Seems like the paths are mixed up now?

**Comment by alexander-nitsche** [comment]
I can confirm that. Please checkout the PR and confirm that this solved the problem.
