### ISSUE TITLE
Screenshots to wide

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#70]
My screenshots are 994 px wide now, even though I have defined 

``

        "options": [
          {
            "action": "resizeWindow",
            "width": 640,
            "height": 640
          }
        ]
``

It seems like this stopped working?

**Comment by alexander-nitsche** [comment]
I assume that you executed the screenshot runner with a specific actions ID and therefore the actions of ID `options` have not been executed?

**Comment by linawolf** [comment]
yeah right, that was it.
