### ISSUE TITLE
Add a comment about source of the code snippet

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#71]
Could we add a comment about where the code came from to the code snipped files maybe? Maybe even the version of the extension?

**Comment by alexander-nitsche** [comment]
So what about supporting the `:caption:` tag of the code directive as we do similarly for the figure directive?

**Comment by linawolf** [comment]
I would greatly support supporting the tags of the code directive but would put that in another ticket

What I am talking about here is a rest comment so you as a documentation author can have a look at the greater context when you are working with the snippets in your documentation.
