### ISSUE TITLE
Make code snippets of xml

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#72]
Flex form generations and such

**Comment by alexander-nitsche** [comment]
You can generally add a complete code snippet of any kind of code type by
```
{"action": "createCodeSnippet", "sourceFile": "typo3/sysext/core/Configuration/Resource/Driver/LocalDriverFlexForm.xml"}
```
Do you want to be able to extract XML paths as you can with PHP arrays?

**Comment by linawolf** [comment]
yes, it would be very usefull to have paths

**Comment by linawolf** [comment]
and we would have to detect or configure the language.

What I am getting now is:

``
.. code:: php

   <T3DataStructure>
       <sheets>
           <sDEF>
``

**Comment by alexander-nitsche** [comment]
In the end this issue is about 
> yes, it would be very usefull to have paths

Would you provide an example of an XML path extraction: What comes in and what gets out?
