### ISSUE TITLE
Make code snippets of classes

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#73]
There are many cases where user funcs are implemented or the such

**Comment by alexander-nitsche** [comment]
You can generally add a complete code snippet of any kind of code type by

{"action": "createCodeSnippet", "sourceFile": "typo3/sysext/impexp/Classes/Export.php"}

Do you want to be able to extract PHP methods as you can with PHP arrays?

**Comment by linawolf** [comment]
It would be wonderfull if we could exclude things like the top-comment
``
/**
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */
`` 
And it would be useful to only limit it to one or several functions. It is important we keep the use-statements

``
use TYPO3\CMS\Backend\Form\FormDataProvider\TcaSlug;
``

Then we also need code snippets from `ext_localconf.php`  However we have no functions there and the line-numbers often change between versions...

**Comment by linawolf** [comment]
See #74 about the `caption`

**Comment by linawolf** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/48202465/117568215-67b3a280-b0bf-11eb-941b-af1fed6b5023.png)

This is what I would need:
![image](https://user-images.githubusercontent.com/48202465/117568238-887bf800-b0bf-11eb-8648-a45fc2e01cd9.png)
