### ISSUE TITLE
Support code-directive tags

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#74]
Lets support 

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/Codeblocks.html
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

I would like to support the following: :caption, :linenos:, :lineno-start:, :emphasize-lines: and the language where it cannot be deduced automatically.

**Comment by linawolf** [comment]
Lets have a look at the options:

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/Codeblocks.html
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

I would like to support the following: `:caption`, `:linenos:`, `:lineno-start:`, `:emphasize-lines:` and the language where it cannot be deduced automatically.

**Comment by alexander-nitsche** [comment]
Hi lina, the keywords in a PR comment to close a related issue automatically by merging the PR are

- Fixes: #74
- Fixed: #74
- Fix: #74
- Closes: #74
- Closed: #74
- Close: #74

Custom human understandable commands like 

- solves #74

do not work though.

See https://guides.github.com/features/issues/.
