### ISSUE TITLE
Wrong language in code snippets

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#75]
Taking code snippets of xml files the output is defined as PHP:

{"action": "createCodeSnippet", "sourceFile": "typo3/sysext/core/Configuration/Resource/Driver/LocalDriverFlexForm.xml"}

``
.. code:: php

   <T3DataStructure>
       <sheets>
           <sDEF>
``

**Comment by alexander-nitsche** [comment]
What about changing the default reST file name from `{sourceFileName}.rst.txt` to `{sourceFileName}.{sourceFileExt}.rst.txt` to prevent basically accidental overwriting?

**Comment by linawolf** [comment]
Why don't we make the filename required just like with the Screenshots? Same thing with searching etc applies here. At least I have always set it.

**Comment by alexander-nitsche** [comment]
> Why don't we make the filename required just like with the Screenshots? Same thing with searching etc applies here. At least I have always set it.

See issue #83.

**Comment by linawolf** [comment]
Is solved
