### ISSUE TITLE
No box gets drawn

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#76]
Scenario:

`` 

          {
            "action": "setScreenshotsDefaultTable",
            "table": "tx_styleguide_elements_basic"
          },
          {
            "action": "setScreenshotsDefaultUid",
            "uid": {
              "action": "getUidByField",
              "table": "tx_styleguide_elements_basic",
              "field": "sys_language_uid",
              "value": 0
            }
          },
          {
            "action": "goToField",
            "fields": "input_1"
          },
          {
            "action": "drawBox",
            "selector": ".formengine-field-item-description"
          },
          {
            "action": "makeScreenshotOfElement",
            "fileName": "Label"
          },
`` 

Result: No box around the label

**Comment by alexander-nitsche** [comment]
Looks fine on my side:
![tx_styleguide_elements_basic_input_1_element](https://user-images.githubusercontent.com/20297232/117614736-0d6f1c00-b169-11eb-9339-51c33293ba61.png)

**Comment by linawolf** [comment]
Ist gelöst
