### ISSUE TITLE
Write protection comment is ignored

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#77]
When I remove the line 
``
.. Automatic screenshot: Remove this line if you want to manually change this file
``

from a code snippet, the file still gets overridden by the backend tool

**Comment by alexander-nitsche** [comment]
Yes, this is not implemented yet.

**Comment by linawolf** [comment]
That is the ideal. But if we just override edited files people would just put their files in another place. 

I had the idea: Warning, 5 of your files are edited manually. Have a look if they can be replaced by automatic screenshots / code snippets now.

**Comment by linawolf** [comment]
If we do not use write protection we should change the line of the comment... As this confuses people

**Comment by linawolf** [comment]
Will be solved by #228
