### ISSUE TITLE
Simple editor and Advanced Editor in Intoduction Package

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-screenshots#94]
I need a simple editor (group simple-editors) and an advanced editor (group advanced editors) for the introduction package. How can I create them?

**Comment by alexander-nitsche** [comment]
Will have to check this tomorrow. There is already a simple editor with name `editor` and you need an additional advanced editor with username `advanced-editor`, right?

**Comment by linawolf** [comment]
the user "editor" currently has no rights whatsoever. Therefore he will just be shown an empty, white page. He should be in the group simple-editors however. And then I would need another user, "advanced-editor" who is in the corresponding group
